// Code generated by MockGen. DO NOT EDIT.
// Source: currency/internal/handler/currency_server.go
//
// Generated by this command:
//
//	mockgen -source=currency/internal/handler/currency_server.go -destination=currency/internal/handler/mocks/mock_currency_service.go -package=mock_handler
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	reflect "reflect"

	dto "github.com/Sevn9/currency-screener/currency/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockCurrencyService is a mock of CurrencyService interface.
type MockCurrencyService struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyServiceMockRecorder
	isgomock struct{}
}

// MockCurrencyServiceMockRecorder is the mock recorder for MockCurrencyService.
type MockCurrencyServiceMockRecorder struct {
	mock *MockCurrencyService
}

// NewMockCurrencyService creates a new mock instance.
func NewMockCurrencyService(ctrl *gomock.Controller) *MockCurrencyService {
	mock := &MockCurrencyService{ctrl: ctrl}
	mock.recorder = &MockCurrencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyService) EXPECT() *MockCurrencyServiceMockRecorder {
	return m.recorder
}

// FetchAndSaveCurrencyRate mocks base method.
func (m *MockCurrencyService) FetchAndSaveCurrencyRate(ctx context.Context, baseCurrency string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndSaveCurrencyRate", ctx, baseCurrency)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchAndSaveCurrencyRate indicates an expected call of FetchAndSaveCurrencyRate.
func (mr *MockCurrencyServiceMockRecorder) FetchAndSaveCurrencyRate(ctx, baseCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndSaveCurrencyRate", reflect.TypeOf((*MockCurrencyService)(nil).FetchAndSaveCurrencyRate), ctx, baseCurrency)
}

// GetCurrencyRateFromInterval mocks base method.
func (m *MockCurrencyService) GetCurrencyRateFromInterval(ctx context.Context, reqDto *dto.CurrencyRateRequestDTO) ([]dto.CurrencyRateResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyRateFromInterval", ctx, reqDto)
	ret0, _ := ret[0].([]dto.CurrencyRateResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrencyRateFromInterval indicates an expected call of GetCurrencyRateFromInterval.
func (mr *MockCurrencyServiceMockRecorder) GetCurrencyRateFromInterval(ctx, reqDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyRateFromInterval", reflect.TypeOf((*MockCurrencyService)(nil).GetCurrencyRateFromInterval), ctx, reqDto)
}
