grpc_client_config:
  currency_service_url: "localhost:50051"
  timeout_seconds: 30

gateway_service_config:
  host: localhost
  port: ":8082"
  timeout_seconds: 30

auth_api_service:
  base_url: "http://localhost:8082"
