grpc_service_config:
  host: localhost
  port: "50051"
  timeout: 30

management_service_config:
  host: localhost
  port: "8080"
  timeout: 30


currency_api_config:
  api_url: "https://latest.currency-api.pages.dev"


database_postgres:
  host: localhost
  port: 5432
  username: postgres
  password: secret123
  dbname: currencyDb

# logging:
#   level: info
#   format: json
