apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-generator
  template:
    metadata:
      labels:
        app: auth-generator
    spec:
      containers:
      - name: auth-generator
        image: artyomyatsenko/final-task-auth-generator:latest
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_TOKEN_LIFETIME
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-generator
spec:
  selector:
    app: auth-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080