apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-cron
  labels:
    app: currency-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-cron
  template:
    metadata:
      labels:
        app: currency-cron
    spec:
      containers:
        - name: cron
          image: currency-cron:latest
          imagePullPolicy: IfNotPresent
          args: ["--config=/internal/config/config.yaml"]
          volumeMounts:
            - name: config-storage
              mountPath: /internal/config/
              readOnly: true
      volumes:
        - name: config-storage
          configMap:
            name: currency-config