# deploy/helm/redis-values.yaml
auth:
  enabled: true
  password: RedisPassword

architecture: standalone # Для теста хватит одной ноды (без репликации)

master:
  persistence:
    enabled: false
  resources:
    limits: {}
    requests:
      memory: 128Mi
      cpu: 100m